definitions:
  item.Priority:
    enum:
    - low
    - normal
    - high
    type: string
    x-enum-comments:
      PriorityHigh: high
      PriorityLow: low
      PriorityNormal: normal
    x-enum-varnames:
    - PriorityLow
    - PriorityNormal
    - PriorityHigh
  types.BadRequestResponse:
    properties:
      body:
        type: string
      code:
        default: 400
        type: integer
    type: object
  types.Message:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: string
      long:
        type: string
      priority:
        $ref: '#/definitions/item.Priority'
      title:
        type: string
    type: object
  types.NotFoundResponse:
    properties:
      body:
        type: string
      code:
        default: 404
        type: integer
    type: object
  types.Response-array_types_Message:
    properties:
      body:
        items:
          $ref: '#/definitions/types.Message'
        type: array
      code:
        default: 200
        type: integer
    type: object
  types.Response-bool:
    properties:
      body:
        type: boolean
      code:
        default: 200
        type: integer
    type: object
  types.Response-types_Message:
    properties:
      body:
        $ref: '#/definitions/types.Message'
      code:
        default: 200
        type: integer
    type: object
  types.UnauthorizedResponse:
    properties:
      body:
        type: string
      code:
        default: 401
        type: integer
    type: object
info:
  contact:
    name: Issues
    url: https://github.com/ZNotify/server/issues
  description: This is Znotify api server.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Notify API
  version: "1.0"
paths:
  /:
    get:
      description: Provide UI
      produces:
      - text/html
      responses:
        "200":
          description: html
          schema:
            type: string
      summary: Web Index
  /{user_id}:
    post:
      consumes:
      - text/plain
      description: Send notification to user_id
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: string
      - description: content
        in: body
        name: string
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Response-types_Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.BadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/types.UnauthorizedResponse'
      summary: Send notification
    put:
      consumes:
      - text/plain
      description: Send notification to user_id
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: string
      - description: content
        in: body
        name: string
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Response-types_Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.BadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/types.UnauthorizedResponse'
      summary: Send notification
  /{user_id}/{id}:
    delete:
      description: Delete message record with id
      parameters:
      - description: Secret of user
        in: path
        name: user_secret
        required: true
        type: string
      - description: ID of message
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Response-bool'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/types.UnauthorizedResponse'
      summary: Delete message record
    get:
      description: Get message record detail of a message
      parameters:
      - description: Secret of user
        in: path
        name: user_secret
        required: true
        type: string
      - description: ID of message
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Response-types_Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.BadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/types.UnauthorizedResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.NotFoundResponse'
      summary: Get message record detail
  /{user_id}/record:
    get:
      description: Get records
      parameters:
      - description: Secret of user
        in: path
        name: user_secret
        required: true
        type: string
      - description: The number of records to skip
        in: query
        name: skip
        type: integer
      - default: 20
        description: The number of records to return
        in: query
        maximum: 100
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Response-array_types_Message'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/types.UnauthorizedResponse'
      summary: Get record
  /{user_id}/send:
    post:
      description: Send notification to user_id
      parameters:
      - description: Secret of user
        in: path
        name: user_secret
        required: true
        type: string
      - default: Notification
        description: Message Title
        in: formData
        name: title
        type: string
      - description: Message Content
        in: formData
        name: content
        required: true
        type: string
      - description: Long Message Content (optional)
        in: formData
        name: long
        type: string
      - default: Normal
        description: The priority of message
        enum:
        - low
        - normal
        - high
        in: formData
        name: priority
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Response-types_Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.BadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/types.UnauthorizedResponse'
      summary: Send notification
    put:
      description: Send notification to user_id
      parameters:
      - description: Secret of user
        in: path
        name: user_secret
        required: true
        type: string
      - default: Notification
        description: Message Title
        in: formData
        name: title
        type: string
      - description: Message Content
        in: formData
        name: content
        required: true
        type: string
      - description: Long Message Content (optional)
        in: formData
        name: long
        type: string
      - default: Normal
        description: The priority of message
        enum:
        - low
        - normal
        - high
        in: formData
        name: priority
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Response-types_Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.BadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/types.UnauthorizedResponse'
      summary: Send notification
  /{user_id}/token/{client_id}:
    put:
      description: Create or update token of device
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: string
      - description: client_id should be a valid UUID
        in: path
        name: client_id
        required: true
        type: string
      - description: channel can be used. Sometimes less than document.
        enum:
        - TelegramHost
        - WebSocketHost
        - FCM
        - WebPush
        - WNS
        in: formData
        name: channel
        required: true
        type: string
      - description: token
        in: formData
        name: token
        type: string
      - description: Additional info about client
        in: formData
        name: info
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Response-bool'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.BadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/types.UnauthorizedResponse'
      summary: Create or update token
  /{user_id}/token/{device_id}:
    delete:
      description: Delete token of device
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: string
      - description: device_id
        in: path
        name: device_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Response-bool'
      summary: Delete token
  /alive:
    get:
      description: If the server is alive
      produces:
      - text/plain
      responses:
        "204":
          description: No Content
          schema:
            type: string
      summary: Server Heartbeat
  /check:
    get:
      parameters:
      - description: user_id
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Response-bool'
      summary: Check if the user_id is valid
  /docs:
    get:
      produces:
      - text/plain
      responses:
        "301":
          description: Moved Permanently
          schema:
            type: string
      summary: Redirect to docs
swagger: "2.0"
