name: CI

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [ frontend_update ]

env:
  IMAGE_NAME: notify-api
  TEST_IMAGE_NAME: notify-api-test

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Fetch frontend asset
        run: |
          wget https://github.com/ZNotify/frontend/releases/download/bundle/build.zip
          unzip build.zip
          rm build.zip
          mv build static

      - name: Build Server
        run: go build -v github.com/ZNotify/server

      - name: Bundle
        run: zip server.zip server users.txt

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "bundle"
          prerelease: true
          files: server.zip

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@master

      - name: Log into Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log into GitHub Package
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Release metadata
        id: meta
        uses: docker/metadata-action@master
        with:
          tags: |
            type=ref,event=branch
          images: zxilly/${{ env.IMAGE_NAME }},ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}

      - name: Extract Test metadata
        id: metatest
        uses: docker/metadata-action@master
        with:
          tags: |
            type=ref,event=branch
          images: ghcr.io/${{ github.repository_owner }}/${{ env.TEST_IMAGE_NAME }}

      - name: Build and push Release Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}

      - name: Build and push Test Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: Test.dockerfile
          tags: ${{ steps.metatest.outputs.tags }}
          labels: ${{ steps.metatest.outputs.labels }}
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}


      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const response = await github.request("GET /${{ env.OWNER }}/packages/container/${{ env.PACKAGE_NAME }}/versions",
              { per_page: ${{ env.PER_PAGE }}
            });
            for(version of response.data) {
                if (version.metadata.container.tags.length == 0) {
                    console.log("delete " + version.id)
                    const deleteResponse = await github.request("DELETE /${{ env.OWNER }}/packages/container/${{ env.PACKAGE_NAME }}/versions/" + version.id, { });
                    console.log("status " + deleteResponse.status)
                }
            }
        env:
          OWNER: orgs/ZNotify
          PACKAGE_NAME: notify-api
          PER_PAGE: 100