name: Pull Request CI

on:
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  tests:
    needs: [ lint ]
    uses: ./.github/workflows/tests.yml

  build:
    needs: [ tests ]
    uses: ./.github/workflows/build.yml

  sdk-tests:
    needs: [ build ]
    uses: ./.github/workflows/sdk-tests.yml
