name: Build Release

on:
  workflow_call:

env:
  IMAGE_NAME: notify-api

permissions: write-all

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true

      - name: Fetch frontend asset
        run: |
          wget https://github.com/ZNotify/frontend/releases/download/bundle/build.zip
          unzip build.zip
          rm build.zip
          mv build static

      - name: Build Linux
        run: go build -v github.com/ZNotify/server -o server-linux

      - name: Build Windows
        run: go build -v github.com/ZNotify/server -o server-windows.exe

      - name: Build MacOS
        run: go build -v github.com/ZNotify/server -o server-macos

      - name: Bundle
        run: zip server.zip users.txt server-linux server-windows.exe server-macos

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "bundle"
          prerelease: true
          files: server.zip