name: Build Release

on:
  workflow_call:
  workflow_dispatch:

env:
  IMAGE_NAME: notify-api

permissions: write-all

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: server

      - name: Bundle
        run: zip server.zip server-linux server-windows.exe server-macos

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          files: server.zip