name: Release binary to GitHub Release

on:
  workflow_call:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3

      - name: Release production binary
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          files: |
            server-linux/server-linux
            server-windows/server-windows.exe
            server-macos/server-macos

      - name: Release test binary
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "test"
          prerelease: true
          files: |
            server-linux/test-server-linux
            server-windows/test-server-windows.exe
            server-macos/test-server-macos
