name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
  repository_dispatch:
    types: [ frontend_update ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.17', '1.18' ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Fetch frontend asset
        run: |
          wget https://github.com/ZNotify/frontend/releases/download/bundle/build.zip
          unzip build.zip
          rm build.zip
          mv build static

      - name: Run tests
        run: go test ./...

  release:
    uses: ./.github/workflows/release.yml
    needs: [ test ]
    if: github.event_name == 'push' || github.event_name == 'repository_dispatch'
    secrets: inherit

  docker:
    uses: ./.github/workflows/docker.yml
    needs: [ test ]
    if: github.event_name == 'push' || github.event_name == 'repository_dispatch'
    secrets: inherit
